---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ $.Values.app.namespace }}
  labels:
    app.kubernetes.io/id: '{{ $.Values.app.uid }}'  
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.app.routename }}
  namespace: {{ $.Values.app.namespace }}
  labels:
    app.kubernetes.io/id: '{{ $.Values.app.uid }}'  
spec:
  to:
    kind: Service
    name: {{ $.Values.app.servicename }}
  port:
    targetPort: {{ $.Values.app.portname }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.app.appname }}
  namespace: {{ $.Values.app.namespace }}
  labels:
    app: {{ $.Values.app.labels }}
    app.kubernetes.io/id: '{{ $.Values.app.uid }}'
spec:
  replicas: {{ $.Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ $.Values.app.appname }}
  template:
    metadata:
      labels:
        app: {{ $.Values.app.appname }}
    spec:
      containers:
      - image: {{ $.Values.app.image }}
        imagePullPolicy: Always
        name: {{ $.Values.app.imagename }}
        ports:
        - containerPort: {{ $.Values.app.port }}
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/id: '{{ $.Values.app.uid }}'
  name: {{ $.Values.app.servicename }}
  namespace: {{ $.Values.app.namespace }}
spec:
  ports:
  - name: {{ $.Values.app.portname }}
    port: {{ $.Values.app.port }}
    protocol: {{ $.Values.app.protocol }}
    targetPort: {{ $.Values.app.port }}
  selector:
    app: {{ $.Values.app.appname }}
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.app.routename }}
  namespace: {{ $.Values.app.namespace }}
  labels:
    app.kubernetes.io/id: '{{ $.Values.app.uid }}' 
spec:
  to:
    kind: Service
    name: {{ $.Values.app.servicename }}
  port:
    targetPort: {{ $.Values.app.portname }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None 
